### ISSUE TITLE
UX User Testing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#125]
## Purpose of this issue:
- [x] Store the UX user testing sessions
- [x] Store who is assigned to work on them and whether remote or in person
- [x] Link to the Figma prototype
- [x] Link to User Testing script(s)
- [x] Link to User Testing Feedback Form (to be filled in by one of our team)
- [x] Discuss which elements we feel are important and require wireframe changes via the notion link (refer to Documentation section in this issue)

## Roles
Every User Testing session must be attended by min. 2 people (1 from Tempo / 1 from Yalla)
- Tempo: Leads the interview with the user
- Yalla: Documents the feedback throughout the session 

## Documentation
All scripts stored here: https://www.notion.so/User-Testing-8f045c9ac9b749c5b9266f8711113252

All feedback and agreed wireframe changes stored here: https://www.notion.so/User-Testing-Feedback-758266fb9453470486b92ada0d78f23a

## Prototypes
**Member**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=187%3A119&scaling=scale-down

**Customer**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=347%3A8218&scaling=scale-down

**Spend Partner**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=381%3A2861&scaling=min-zoom

**Staff**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=325%3A4243&scaling=min-zoom

### Monday 16th March
**Customer & Member Testing**
- Location: Lache Community Center
- Users: 3
- 11-11.30 - Gemma (Kat)
- 11.45-12.15 Sharon (Karen)
- 12.30-13.00 Christina (Carys)
- Assigned: @harrietepugh (in person) @jema28 (in person)

**Customer & Member Testing**
- Location: The Cunliffe Centre
- Users: 4
- 14.00-14.30 - Member 1
- 14.30-15.00 - Member 2
- 15.00-15.30 - Debbie (Adewale)
- 15.30-16.00 - Nicole (Kat/Karen)
- Assigned: @harrietepugh (in person) @jema28 (in person)

**Spend Partner Testing**
- Location: Tower of London, St Katharine's & Wapping, London EC3N 4AB
- Users: 3
- 15.00 - 17.00
- Assigned: @JonnyBuck16 (in person) @dupreesi (remote)

### Tuesday 17th March
**Staff Testing**
- Location: REMOTE
- Users: 2
- 12.30 - 13.00 - Brian (Howard)
- 13.30 - 14.00 - Sarah (Laura)
- Assigned: @harrietepugh  @jema28 (remote)

### Wednesday 18th March
**Customer & Member Testing**
- Location: Reset Recovery Centre, 183 Whitechapel Rd, Shadwell, London E1 1DN
- Users: ???
- 10.30-12.00
- Assigned: Tempo @harrietepugh (in person) @JonnyBuck16 (in person) @jema28 (in person)

**Customer & Member Testing**
- Location: Mind in Haringey, 73C Stapleton Hall Rd, Stroud Green, London N4 3QF
- Users: ???
- 13.30-16.00
- Assigned: @harrietepugh (in person) @JonnyBuck16 (in person) & @jema28 (in person)

### Thursday 19th March

**Customer Testing**
- Location: 18-21 Morley Street, London SE1 7QZ 
- Users: 2
- 11.00-12.00
- Assigned: @harrietepugh (in person) @JonnyBuck16 (in person) & @dupreesi (remote)

**Customer & Member Testing**
- Location: SU Room, 590 Seven Sisters Road, London, N15 6HR
- Users: ???
- 13.00-16.00
- Assigned: @harrietepugh (in person) @JonnyBuck16 (in person) & @dupreesi (remote)

### Friday 20th March

**Member Testing**
- Location: Tempo Office, Studio 305 Small Meeting Room
- Users: 3
- 11.30 - 12.15 
- 12.30 - 13.15
- 14.00 - 14.45
- Assigned: @harrietepugh  @jema28 (in person)

**Comment by thejoefriel** [comment]
# Monday

**Comment by harrietepugh** [comment]
@thejoefriel @jema28 Just realised that we'll need to establish which persona the members are before testing. In some cases, I know which member the persona is because I've recruited them, but where we are turning up to groups to reach Lloyds and Jackies, we'll just need to work out which they are at the beginning of testing. Should we add a couple of questions at the beginning on member test script?

**Comment by thejoefriel** [comment]
> @thejoefriel @jema28 Just realised that we'll need to establish which persona the members are before testing. In some cases, I know which member the persona is because I've recruited them, but where we are turning up to groups to reach Lloyds and Jackies, we'll just need to work out which they are at the beginning of testing. Should we add a couple of questions at the beginning on member test script?

We covered this in our call yesterday so just documenting that and that the main thing we'll need to know is if they are a lloyd as for them we would just need to show them a card. Do we need to design this ahead of Monday probably?

**Comment by thejoefriel** [comment]
@harrietepugh @JonnyBuck16 Here's the script for the Member testing: https://www.notion.so/Member-7b8e7ac44bbc44498a9ce840c6f6b7d8

As you can see we encourage them to just play around with the app as much as possible to then see what they do, but then we would get them to do further specific tasks if that specific area of the app hadn't yet been tested. 

I'll write up the others now but let me know if any questions at all! Feel free to comment on the notion page for suggestions on other bits or stuff you want changed.

**Comment by thejoefriel** [comment]
Hi @harrietepugh @JonnyBuck16 initial drafts of all three user testing scripts are in there now. Please feed in with other tasks etc you might like them to do :) 

https://www.notion.so/User-Testing-8f045c9ac9b749c5b9266f8711113252

**Comment by JonnyBuck16** [comment]
Hey @thejoefriel just been through the Customer and Spend Partner scripts - really good!

For Spend Partners - can we add the following:

Now using the platform can you act out how you would use it as if you were serving a customer.

Is everything clear? 
Is anything missing that you'd ordinarily ask the customer for or need?
What do you think of the length of time this takes to complete?
How well would this work with your existing systems?
What do you think of the unsuccessful transaction page?
Would you be happy explaining to a customer they haven't got enough Time Credits? 

Okay, now we are going to go to the insights section. Ordinarily only managers and business owners would see this, rather than everybody who works at a Spend Partner. What are your initial thoughts on it's content?

Is anything missing?
What do you think of the headline stats on the right hand-side, would you like to see anything else?
Does everything make sense?

**Comment by thejoefriel** [comment]
Thanks @JonnyBuck16 ! Have gone through and added those bits

@harrietepugh are you happy with the Members script?

**Comment by jema28** [comment]
Link to where we're storing User Testing Feedback, split up into Synthesised Changes and All Feedback: https://www.notion.so/User-Testing-Feedback-758266fb9453470486b92ada0d78f23a
