### ISSUE TITLE
Review Time Credit Flow

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#22]
@JudeLuckett @JonnyBuck16 @harrietepugh - I've gone ahead and visualised the total flow to a Time Credit from when Tempo first distributes some (or a Customer buys some) through to the point that they are spent. 

You can see it at the top of the whimsical board: https://whimsical.com/Mu7s9dj5Wv2Hph6Y3Vi7wW

I've also included notes on what data is stored about the tracked Time Credits and when, to confirm an overview of tracking TCs. So as you can see while we don't track the specific TC, we can still attribute Time Credits to programmes at the point they are given out to members, and also then see the % that members go on to spend them. So for example, we could know that a Customer part of a Programme has given 15 credits to John, and then we can also see that John on average has spent % of his Time Credits this past month etc. 

Do you mind having a look and letting me know what you think? I think it's generally in line with what we've all been discussing, but want to make sure!

**Comment by harrietepugh** [comment]
lol I replied in an email - should I reply here generally? May take a couple of weeks to get used to all the different comms channels!

**Comment by JudeLuckett** [comment]
I have had a look over this and I think it follows everything. I think in the data workshop the data flows and outputs (assume that is what we will cover there) will link in to this

**Comment by JudeLuckett** [comment]
I also have added a couple of notes about a new customer user type - a council partner who is delivering a programme, so acting like a network manager in terms of distributing credits and managing data. This is another persona - @JonnyBuck16 we might need to work that up just to make sure we don't miss anything even if we then don't develop all their needs immediately?

**Comment by JonnyBuck16** [comment]
No problems. I’ll aim to have it be done by the end of today.

Otherwise it’ll fall well behind!


[8732FE65]
Jonny Buck
Product Owner

[Telephone]
0292 056 6132 | 07429 257 581
[World]
wearetempo.org<http://www.wearetempo.org/> | timecredits.com<https://timecredits.com/>
[Marker]
Studio 301, Pelican House, 144 Cambridge Heath Rd, London, E1 5QJ
@tempo_tweets<https://twitter.com/tempo_tweets> | facebook.com/timecredits<http://facebook.com/timecredits>
Sign up to our newsletter<https://bit.ly/2y6a4yU>
[cid:image011.png@01D5F139.E83E13F0]
[cid:image012.png@01D5F139.E83E13F0]

Tempo is a Limited Company Registered in England and Wales: Tempo Time Credits Limited No.06593956, and Registered Charity No. 1135143. The information contained in this e-mail and any attachments is confidential and may be legally privileged. If you have received it in error, you are on notice of its status. It is intended solely for the addressee. Any unauthorised use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately and delete the e-mail and any attachments from the system.
