### ISSUE TITLE
Agree Data Architecture

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#55]
**This issue is to discuss the data architecture which we'll be talking through in the lead up to the data workshop (05/03) and beyond - so all documentation should go here.**

**Comment by thejoefriel** [comment]
Hey @JudeLuckett ahead of the data workshop on Wednesday, here's a list of initial things it'd be great to know:

- What existing data do you have and will need to migrate? Will you be able to show us the list at the workshop so we can discuss?
- What are the key problems with how the current data is structured that meant you couldn't get the information you wanted from it? Do you have access to any schemas, models etc you would be able to send across? Or the log in to the database so we can investigate?
- Questions about the data in the data spreadsheet:
    - What data points are you wanting to collect for wellbeing data?
    - What data points are you wanting to collect for demographic data?
    - What data points are you wanting to collect for motivational data?
- Are there any particular considerations you want us to take into account when thinking through the data? Even if it seems obvious please include so we don't miss anything! 
- What data do you need to visualise and how do you want it visualised?

It would also be great to better understand your CRM flow, but I think this may be too much for this session and could be worth discussing separately. However, if there are any key points of consideration let us know. 

**Goals**
I've also put together an initial assumption on your goals are for the workshop and final presentation of our suggested data architecture and approach:
- Confident there is a plan for scalability
- Confident we aren't building a data architecture that gets you stuck in a corner (i.e. doesn't include everything and doesn't have the option to add to it, meaning that you can't change anything in future)
- Confident existing data can be transferred across
- Understanding of how the data maps to the journeys

If there are others please add them below. This can then lead to us updating our planned itinerary for the day. 

Finally as I've mentioned, but just to confirm, it is very unlikely that the data architecture for a product is 100% fixed at the point of creation and never needs to change. Ultimately there will always be discoveries, things that arise in the dev process and from user testing etc that means we will need to make changes. And generally this is completely fine - it becomes trickiest at the point when we have live data on there. However, the purpose of this work now is to try and think ahead as much as possible beyond release 1 to minimise these changes for you. :)

**Comment by JudeLuckett** [comment]
List of current data and my initial thoughts on migration
[Tempo current data structure.xlsx](https://github.com/yalla-coop/tempo/files/4299371/Tempo.current.data.structure.xlsx)

**Comment by JudeLuckett** [comment]
**Goals**
Confident there is a plan for scalability
Confident we aren't building a data architecture that gets you stuck in a corner (i.e. doesn't include everything and doesn't have the option to add to it, meaning that you can't change anything in future)
Confident existing data can be transferred across
Understanding of how the data maps to the journeys
*** Confident the data structure and storage is secure
* Confident we can get Tempo KPI information from the data**

**Comment by JudeLuckett** [comment]
**What are the key problems with how the current data is structured that meant you couldn't get the information you wanted from it?** 

I think it's mainly about how we access the data and how complete it is. It comes in CSV downloads of specific sets rather than everything on the forms. We also don't collect everything we would like to (eg earn/spend data is not collected on the paper currency, and we have **lots** of gaps due to people not providing information). On the newer tool which we are not using, the data doesn't give us member details associated to region or programme or city, so we don't know which mailing list to add them to. 

Notes from Fi (who manages data off the Reporting Tool) on issues:
**Reporting/ data notes**
•	Do groups only report when they run out of time credits?
•	Why are we downloading inactive members?
•	Why are we downloading inactive system users and groups?
•	Can you pull off a list of all active groups alongside system users to see if they have an active one?
•	Only CST to add groups/projects to reporting tool please to avoid them being set up incorrectly
•	Can you have more admin levels to the reporting tool so NM’s can access data but not set up projects and groups etc?
•	Need to be able to extract the earn sheet without inactive members so we don’t have to manually count - asked red bullet to put a column in that tells us if active or not
•	Can’t download excel spreadsheets onto sharepoint only computer – data issue
•	Permission to contact - make it really clear to encourage people to sign up to newsletters
•	More than one group lead (or deputy) per group in case one is ill, leaves, mat leave, annual leave
•	Have a way member can sign up themselves but also a way the group lead can sign them up so we can capture members contact details and permission to contact question
•	System user – why is there no data in the last logged in column? 
•	Why has system user got created by (person) data but not created date?
•	How can we remove old members but not lose totals?
•	Bulk upload spreadsheet does not match new fields so can’t use – red bullet looking at this now
•	Make fields in membership form compulsory for required fields
•	If you make project or group inactive everything is made inactive including system users – system users can be active in one group and inactive in another
•	Careful about what info is downloaded when looking for reporting figures –  all the contact details of active and inactive members is also downloaded
•	Search function does not work very well – we can’t search system users or their email addresses, have to put exact group/project names in to find it, and if put a space in you can’t find it
•	why is there a contact details for a group and system user for group? Don't need contact info one - we can't export this info and it is confusing







**Do you have access to any schemas, models etc you would be able to send across?** 
No, not of the data structure. I'm not sure how that was previously developed. We have this summary of our digital tools 
[digital systems map.pptx](https://github.com/yalla-coop/tempo/files/4299445/digital.systems.map.pptx)


**Or the log in to the database so we can investigate?**
I've asked our old agency if there is a backed database login - otherwise it's the Reporting Tool login in the Admin Spreadsheet

**Comment by JudeLuckett** [comment]
Questions about the data in the data spreadsheet:
What data points are you wanting to collect for wellbeing data?
This will be taken from our annual survey. It might be a baseline and follow up or single survey. Questions to follow.

**What data points are you wanting to collect for demographic data?**
Age
Gender
Ethnic background
Sexuality
Disability
Caring responsibilities
Employment
Income
Religion

What data points are you wanting to collect for motivational data?
To be discussed/finalised but: 
Spend Partner (select up to 3)
-	To reach new audiences
-	To gain more customers
-	To make use of our spare capacity 
-	To market our organisation
-	To do something charitable/give back to the community
-	To support volunteers
-	To encourage people to volunteer here
-	To meet my funding/contractual targets
-	Other (please specify)
Customer (select up to 3)
-	To say thank you to our existing volunteers
-	To retain our existing volunteers for longer
-	To recruit new volunteers 
-	To diversify our volunteers
-	To give people opportunities they may not otherwise be able to afford
-	To prompt our volunteers to do things that are good for them
-	To create social activities for volunteers to do together
-	To support service user engagement 
-	Other
Member (select up to 3) 
-	To go on days out with friends/family/kids/grandkids
-	To meet new people or make new friends
-	To save money
-	To have new experiences
-	To give something back to my community or make a difference
-	To learn new skills
-	To help me get a job
-	To get out more or be more active
-	To go on trips with others
-	To access exclusive opportunities
-	To feel thanked and valued for my time
-	To improve my health or mental health
-	To give them to other people I know who can use them
-	Other

**Comment by JudeLuckett** [comment]
**What data do you need to visualise and how do you want it visualised?**
At the moment we visualise very little. I don't know that we have answers to this - it may come out of the work we are doing on standardising how we operate as if we agree a standard report for customers or commissioners that would be good to be able to copy/share. Be good to discuss

**Comment by JudeLuckett** [comment]
**Are there any particular considerations you want us to take into account when thinking through the data? Even if it seems obvious please include so we don't miss anything!**

- Data security and privacy e.g. downloading data, ability to anonymise or remove personal data. 
- Ability to add or remove or edit data - permissions and people using systems wrongly
- To add more!

**Comment by JudeLuckett** [comment]
**Are there any particular considerations you want us to take into account when thinking through the data? Even if it seems obvious please include so we don't miss anything!**

Very varied digital confidence (and Excel confidence!) among staff. i think we should consider essential top line stats we can visualise and then if there are key exports as well as a total export (e.g. contact details or earn/spend totals by group) that would make it easier for people to manage projects without downloading a complicated spreadsheet. Obviously we also need to do some training!

Transition. There will be a period when we run both paper and digital systems and we will need to make the data compatible (even if it's just the ability to add relevant numbers together). Here is the way we currently analyse data on an organisational level 
[Copy of 2019-20 data analysis Q2.xlsx](https://github.com/yalla-coop/tempo/files/4305706/Copy.of.2019-20.data.analysis.Q2.xlsx)

This issue around (not) tracking credits, only people's activity. I think we need to ensure that the data we need can be captured without tracking the credit - or that we are clear about what will not be possible, and able to justify that. I might need a summary of that to share with Ian as this feels like quite an important decision.

Data visualisation; the extent to which we could build a spreadsheet to do this in the medium term to test what people need/what is most useful. If we can set up (I might be able to do this) a template that people can copy data into to create some graphs etc, that might be a good testing/MVP approach.

**Comment by JudeLuckett** [comment]
Anne Marie notes

What are the key problems with how the current data is structured that meant you couldn't get the information you wanted from it? Do you have access to any schemas, models etc you would be able to send across? 

•	data is currently difficult to navigate-everything needs to be downloaded into lots of different spreadsheets and then sorting
•	no data can be moved from one place to another on the current reporting tool
•	we don't know when changes have been made e.g. new system user added etc

Are there any particular considerations you want us to take into account when thinking through the data? Even if it seems obvious please include so we don't miss anything!

•	How would we transition from current reporting requirements and any new measures/systems
•	Data requirements across programmes needs to be more aligned as currently reporting requirements vary hugely 

The big question for us is around transition and how we will manage expectations of staff/commissioners etc and ensuring that we have a chance to test all the data elements before we need to use if 'for real'

**Comment by dupreesi** [comment]
@JudeLuckett @JonnyBuck16 @harrietepugh @thejoefriel
Our DB schema can be viewed here: 
https://dbdesigner.page.link/dvaJspwsedUNo1VZA

**Comment by dupreesi** [comment]
@JudeLuckett @thejoefriel @JonnyBuck16 @harrietepugh @RamyAlshurafa @ashatat  these are some data planning outcomes that require more discussion: 

**1. need of super users (customer type) to be the point of contact for group management**
Context: This is related to the current reporting tool structure (region → locality → programme → hubs → customers → volunteers). We don't have any customers with a 'hub' facilitation role. Hubs support groups to get started from being an activity based model to the formation of an official group (until when they are taking on their own TC admin)

Action: Maybe add this to our db in a new table, e.g. hub_customers considering the following:
- can view all group details such as volunteer transaction data (like customers)
- never more than 1 super customer

**2. Logging of failing TC requests** 
Context: While creating logs of failing transactions due to insufficient funds or other errors there is also a need to log more qualitative data such as feedback from venues not allowing TC transactions due to overbookings etc.

Action: Think about a way to show failed transactions via the app (Release 1) and think about ways of reporting for failed transactions happening outside the digital scope (upcoming releases).

**3. Region missing in programmes table**
Action: Add field "Region" to programmes table

**4. Rejection reasons for TC requests need to also cover partially rejected requests**
Action: consider partially_rejected in free_credit_requests table

**5. Packages need to also consider other purchase options**
Action: consider options such as evaluation support, trainings as part of packages (upcoming releases)

**6. Randomly selected TC distribution**
Context: As part of tracking TC journeys related to programmes we need to create an allocation strategy how to deduct TC from member accounts that earned TC from various programmes. When deducting TC from an account we create a Transactions with the total amout but also sub_transactions which we relate to programmes (so we can track what's been going out from programmes XYZ over time).

Action: Think about ways of how to do such allocations. We could start with random choices for now and then move to something more 'sophisticated' in future.

**7. Add budgets to programme table**
Action: add budget (TC amount on creation) to programm table. can budgets be modified once they're set? 

**8. Activate / deactivate volunteers on customer level**
Action: make sure managers can remove volunteers from specific group (clicking on that group) or from all groups (via viewing list of all volunteers)

**9. Need to see when volunteer got removed from group**
Action: is this covered by deactivation_date by field in volunteer_group table? Think about how to create a history of such activities. 

**10. Ability to mark customers as inactive**
Action: When a customer stops using (giving out) TCs create option so staff can de-activate their accounts.

**11. Marketing option field in db**
Action: Additionally to mailchimp it'd be good to store a flag in the db covering a user's contacting preferences related to marketing purposes (e.g. agreesContact)

**12. Network and partnership managers, central reporting team**
Context: → partnership manager: finds new spend partners and looks after spend network, maintains relationships with those partners (CRM) → network manager: similar responsibilities but for groups → central report team: central admin, data analysis, reporting ...
Action: Decide wether these roles are to be set up as part of tempo user roles.

**13. Idea to allocate groups to programmes to distribute TC**
Action: Think about ways to alter db so we can add groups to a programme and allocate budgets to those (for upcoming releases) 

I hope that covers it all. Let me know if I forgot anything...

**Comment by dupreesi** [comment]
**14. Clarify roles and their permissions**
Action: What roles do we need? And what data should they (not) have access to? Discussion needed. 

**15. Complete data collection for Profiles and Activities*
Action: Need to get a clear sense of what data fields we need to add to each user's profile and also for activities.

**Comment by JonnyBuck16** [comment]
Hey @dupreesi , just added a tonne of comments into the comment above itself. Hope this was the best way of doing this and that some of them help?!

Let me know if you have any questions on them!

**Comment by JudeLuckett** [comment]
Hi @dupreesi I have added a few  more comments in under Jonny's. I think the only outstanding action is the list of profile fields for users...to follow!

**Comment by thejoefriel** [comment]
Hi @JudeLuckett @JonnyBuck16 @harrietepugh here is our suggested database schema:
![Database Schema](https://user-images.githubusercontent.com/19708921/77024867-0d5cfd00-6966-11ea-9a75-e38d8039c23b.jpg)

And here are the general data flows to give a sense of how the user journeys with the app interact with the database:
https://whimsical.com/VS2w9dWpVujxsFEKDUvdPV 

Please let me know if any issues with this or once it is signed off :)

**Comment by JudeLuckett** [comment]
Thanks @thejoefriel . I think we need to add in the user and activity fields in Sheet 2 of this spreadsheet. Can we go over this on our call later? I think it might need a bit of tidying/checking esp on activities as earn/spend are not the same at the moment. Thanks :)

[Tempo Staff Data Exports.xlsx](https://github.com/yalla-coop/tempo/files/4354774/Tempo.Staff.Data.Exports.xlsx)

**Comment by JudeLuckett** [comment]
Note - @JudeLuckett  to check in with @JonnyBuck16 and @harrietepugh to finalise the fields!

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa could do with your brain for something related to this! So for an Spend Activity there are two issues around dates/times. 

1. Some activities will occur on a set date (or a set range of dates) and then stop, whereas others will be ongoing

2. Activities will have certain times they are available for each day in the week it is available

So we need in the database to store the date(s) the activity is on AND the times within this period that it is available for people to attend. 

**Option 1**
We have three fields in the activities section for this:
- Start Date (this would be when the activity starts)
- End Date (this would be when the activity ends - if it's left blank we would assume it means it's ongoing)
- Availability (a varchar field so it would just be a text input where the user could write what they want) 

**Option 2**
We somehow breakout availability to include (an array?) of days and time? So for example an event could be Monday 10am to 5pm, Tuesday 10am to 10pm, Saturday 9am to 3pm.  


What are your thoughts on best approach?

**Comment by JudeLuckett** [comment]
@thejoefriel @RamyAlshurafa 

Just got off a conversation with board about the data architecture and there was a suggestion that a gap in the schema would be a table for 'ticket availability' or similar - so if a spend partner wants to offer X number of tickets (which they can update) then as people spend TC against that activity they would be deducted from the total. Could be useful to think about for future booking/managing offers. Can you let me know what you think and we can discuss? Thanks

**Comment by thejoefriel** [comment]
Thanks for this Jude. @RamyAlshurafa @fadeomar would be good to get your thoughts on this when you get a chance. Probably not a release 1, but just want to make sure it doesn't cause any potential issues to our overall structure?

**Comment by JudeLuckett** [comment]
@thejoefriel this just came up in convo again so glad to see you have picked it up! Can we agree before sign off of the data architecture?

**Comment by RamyAlshurafa** [comment]
Hey @JudeLuckett 
I modified the DB schema to include your suggestion

**Comment by JudeLuckett** [comment]
Thanks @RamyAlshurafa does it make sense? Any questions?

**Comment by RamyAlshurafa** [comment]
everything is okay,
I had a chat with Joe regarding the "Spend Activity" options he suggested and we believe that the second option is the best. so will update the schema and will share it with you

**Comment by RamyAlshurafa** [comment]
@JonnyBuck16 @JudeLuckett @thejoefriel 
here is the updated schema

![tempodb](https://user-images.githubusercontent.com/34629478/77950052-a37f1480-72d0-11ea-935a-7ae6a298df7a.png)
