### ISSUE TITLE
Get all Programmes (Back End)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#605]
__Is this part of a User Journey?__

https://github.com/yalla-coop/tempo/issues/600

---

### Acceptance Criteria:

**Top stats:**
- [x] Total Active Programmes

**Table - Key Info**
- [ ] Programme
- [x] Earn Groups - this is all earn groups currently assigned to the programme
- [x] Members - this is all members who have been reached by the programme, this includes:
     - Currently actively volunteer for an earn group part of the programme
     - Have received credits associated from the programme (gifted, given)     
- [ ] % Spent - % Programme Time Credits given out by Earn Groups that are associated with the Programme - refer to #600 for more details on associating TCs to programmes
- [x] Gifted - Total number of TCs from the programme that have been gifted. NOTE: this means if a TC from a programme is gifted to a member and then that member gifts that TC to another member, that would count as 2 TCs gifted 
- [ ] Status - whether the programme is open or not 

**Table - Other**
- [x] Programme
- [x] Date opened
- [x] End Date (NOTE: end date doesn't impact anything in terms of tracking at the moment. All transactions etc would still be counted beyond this date)
- [x] Region
- [x] Focus - this is the main focus  in the create / edit programme form 

### What we need from Tempo

@harrietepugh @JonnyBuck16  - when we first load the programmes, what order should they be?

**Comment by harrietepugh** [comment]
@thejoefriel I'm checking in with the data team about the order of Progs but just to check, we'll be able to sort by any of the headers by clicking on them right?

Spend % - yes it will be all Time Credits ever given out in a programme
Gift - the gifted stat isn't a % at programme level because it could just end up being 1000s. Its just the number of gifted TCs

Earn Groups and Members - I'm just checking in with the team about which would be most useful but this is a really good question! Maybe we should have both stats!?! I think the main stats should be currently assigned but it might be good to have the historic figure somewhere too...

**Comment by thejoefriel** [comment]
OK @harrietepugh I've updated this following our conversations, including our conversation in #600 to actually show number of times members do a gift rather than number of TCs gifted. Let me know if that works for you or any other issues with how it's laid out above :)

**Comment by harrietepugh** [comment]
Great :)

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
what `?` icon should say?
