### ISSUE TITLE
Pre-loading Activities - List

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#67]
Hi @laurajtempo - hope you had a nice long weekend! 

Just wanted to check in to see if you had the spending partner and the list of activities for us to pre-load?

**Comment by laurajtempo** [comment]
HI Joe, sorry for the delay in getting back, we've been moving offices!

Haringey Arthouse have provisionally agreed - they only have one type of activity, which is a ticket for the cinema at specific times:
https://timecredits.com/spend/1265 - 
2 Time Credits = 1 TICKET TO CINEMA  (MONDAY ALL DAY AND TUES TO FRI BEFORE 5PM)

So the activity could just be '1 ticket to cinema' and this activity would take 2 Time Credits from someone's amount/total? Let me know if you want me to try and clarify anything? Ta

**Comment by thejoefriel** [comment]
Thanks @laurajtempo . Hope the move has been going ok! 

Are there a max number of tickets they would accept do you know?

**Comment by laurajtempo** [comment]
From a member of staff: "I've never been made aware of any, but the line we'd use for that partner is 'when capacity permits' so , if a large group wanted to go, we'd check with ArtHouse first. Most cinemas are ok with it, if your'e not making them turn away paying customers"

 - so not that we're aware of. There are a few partners with capacity limits from what I understand, but this it usually just to ensure they can still have some spots for paying customers, or because there are only a limited number of spaces, like tickets for the theatre or the Ally Pally Fireworks.

**Comment by laurajtempo** [comment]
We could ask Arthouse, but I think we may be better to not limit it for the moment, if that's the current way the currency is accepted?

**Comment by thejoefriel** [comment]
Thanks @laurajtempo 

Final question, are the partner fine to then manually put in the number of time credits. I'm just thinking about the best way to do this as there are two options:

1. User selects 1 x Cinema Ticket from dropdown. This then immediately changes the Credits number to 2. They then have to scan and go through this process for each ticket being bought with Time Credits
2. User selects Cinema Ticket(s) from dropdown. They then manually put in the number of credits (this would rely on the staff knowing the price)

I feel the second is a better option, but wanted to check with you on this first?

**Comment by laurajtempo** [comment]
Option 2 made more sense to the team here too. Currently the partners need to know this, and would hopefully be less effort/work for both parties, rather than have to repeat a process - so we're happy to go with that

**Comment by thejoefriel** [comment]
Thanks @laurajtempo sounds good 👍
