### ISSUE TITLE
To check

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#965]
- [ ] Typo on Employability Tag
- [x] The drop-down for "have you ever volunteered before" jumbles the text when I select the I already volunteer regularly option (see image) and won't let me complete the form with that option
- [x] In the all Earn groups export, the active members is 36, when on the dashboard in the tool, it states 25
- [ ] Nothing displaying postcode, or if they're adults/children
- [x] Adding a spend opportunity after completing the fields doesn't allow for saving
- [x] When setting up a new programme, two more focuses shouldn't be compulsory field
- [ ] spend-venue insights - I can't see the postcodes in the inights section, even when we hold them for members - check if this was in the wireframes and if it's working

**Comment by dupreesi** [comment]
Typo on Employability Tag
-> not fixed, issue created
  The drop-down for "have you ever volunteered before" jumbles the text when I select the I already volunteer regularly option (see image) and won't let me complete the form with that option
-> fixed in 857
  In the all Earn groups export, the active members is 36, when on the dashboard in the tool, it states 25
-> not a bug as stated in 901
  Nothing displaying postcode, or if they're adults/children
-> no in wireframes for an individual earn group member
  Adding a spend opportunity after completing the fields doesn't allow for saving -> fixed in 914
  When setting up a new programme, two more focuses shouldn't be compulsory field
-> not a bug as labelled by tempo in spreadsheet
  spend-venue insights - I can't see the postcodes in the inights section, even when we hold them for members - check if this was in the wireframes and if it's working
-> not fixed, issue created

**Comment by thejoefriel** [comment]
thanks @dupreesi ! Hacve updated the spreadsheeet so will close this
